"Set mapleader
let mapleader = ","
let g:mapleader = ","
filetype on
filetype plugin on

" must set
set nocompatible
set nobackup
set warn

" key and mouse
set backspace=indent,eol,start

" apperence
set number
set ruler
set laststatus=2
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
set modeline
set modelines=1
set showmode
syntax on
set showmatch

set list
set listchars=tab:>-

highlight SpecialKey ctermfg=DarkGray guifg=DarkGray

autocmd ColorScheme * highlight NoneText ctermbg=DarkGray guibg=DarkGray
autocmd ColorScheme * highlight SpecialKey ctermfg=DarkGray guifg=DarkGray
"autocmd ColorScheme * highlight SpecialKey ctermbg=white guibg=white

highlight ExtraWhitespace ctermbg=red guibg=red

" Show trailing whitespace:
match ExtraWhitespace /\s\+$/
" Show trailing whitespace and spaces before a tab:
match ExtraWhitespace /\s\+$\| \+\ze\t/
" Show tabs that are not at the start of a line:
match ExtraWhitespace /[^\t]\zs\t\+/
" Show spaces used for indenting (so you use only tabs for indenting).
match ExtraWhitespace /^\t*\zs \+/
" Switch off :match highlighting.
"match

" set cursorline
autocmd BufReadPost * if line("'\"") && line("'\"") <= line("$") | exe "normal `\"" | endif

if $VIM_HATE_SPACE_ERRORS != '0'
	let c_space_errors=1
endif

" theme and color
colo darkblue

" format
set noexpandtab
set autoindent
set incsearch
set hlsearch
set tabstop=4
set shiftwidth=4
set nowrap
set cindent
set tw=79

" fold
set foldmethod=syntax
set foldnestmax=1
set nofoldenable

" files format support 
set fileformats=unix,dos

" help lang
"set helplang=cn
set enc=utf-8
" set fencs=utf-8,gbk
